apiVersion: v1
kind: ConfigMap
metadata:
  name: ezsales-mkp-front-configmap
  namespace: default
data:
  COM_REPLY_TO_EMAIL: {{ .Values.communication.replyTo.email }}
  COM_REPLY_TO_NAME: {{ .Values.communication.replyTo.name | quote }}
  COM_CLIENTS_SENDINBLUE_BASE_URL: {{ .Values.communication.clients.sendinblue.baseUrl }}
  S3_CLIENTS_SCALEWAY_ENABLED: '{{ .Values.s3.clients.scaleway.enabled }}'
  S3_CLIENTS_SCALEWAY_ENDPOINT: {{ .Values.s3.clients.scaleway.endpoint }}
  S3_CLIENTS_SCALEWAY_REGION: {{ .Values.s3.clients.scaleway.region }}
  NODE_ENV: {{ .Values.env }}
  AUTH_ORIGIN: {{ .Values.front.auth.origin }}