# Default values for EZ Sales MKP Front.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
front:
  enabled: true
  name: ezsales-mkp-front
  namespace: default

  clusterRoleRules:
    - apiGroups:
        - ""
      resources:
        - configmaps
        - secrets
      verbs:
        - get
        - list
        - watch

  logging:
    debug: false
    stdout:
      encoderPattern: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file:
      enabled: true
      rollingPolicy: |
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!-- daily rollover -->
            <fileNamePattern>${ezsales.mkp-front.log.dir}/ezsales-mkp-front_%d{yyyy-MM-dd}.log</fileNamePattern>
        </rollingPolicy>
      encoderPattern: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n%n"
    ezsalesLevel: DEBUG
    nettyLevel: INFO
  restartPolicy: OnFailure
  reloadOnConfigChange: true
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  replicaCount: 1
  image:
    repository: rg.fr-par.scw.cloud/funcscwrecezsalesapivdpn8gpk/ezsales-mkp-front
    tag: 0.0.1
    pullPolicy: Always
    pullSecrets:
      - name: registry-secret

  deployment:
    # Annotations to apply to the deployment
    annotations: {}
    # additionals labels
    labels: {}
    affinity: {}
    hostAliases: []
    #- ip: "127.0.0.1"
    #  hostnames:
    #  - "foo.local"
    #  - "bar.local"
    nodeSelector: {}
    tolerations: []
    envFrom: []
    #  - configMapRef:
    #    name: config-secret
    securityContext:
      runAsUser: 1042
      runAsNonRoot: true
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
    topologySpreadConstraints: []
    # revisionHistoryLimit: 10

  livenessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 3

  readinessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 3

  pdb:
    enabled: false
    minAvailable: ""
    maxUnavailable: "50%"

  podAnnotations: {}

  # How long to wait for EZ Sales MKP Front pods to stop gracefully
  terminationGracePeriod: 30

  # This is the PriorityClass settings as defined in
  # https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass
  priorityClassName: ""

  env: []
  #   - name: ENV_VARIABLE
  #     value: ENV_VARIABLE_VALUE
  #   - name: ENV_VARIABLE_WITH_FROM
  #     valueFrom:
  #       configMapKeyRef:
  #         name: special-config
  #         key: SPECIAL_LEVEL

  additionalPlugins:
  #   - https://path_to_plugin

  service:
    type: ClusterIP
    externalPort: 83
    internalPort: 8093
    internalPortName: http
  # annotations:
  securityContext:
    runAsUser: 1042
    runAsNonRoot: true
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetAverageUtilization: 50
    targetMemoryAverageUtilization: 80
  ingress:
    enabled: true
    ingressClassName: ""
    path: /management
    # Used to create an Ingress record.
    hosts:
      - am.example.com
    annotations:
      #kubernetes.io/ingress.class: nginx
      #ingress.kubernetes.io/configuration-snippet: "etag on;\nproxy_pass_header ETag;\nproxy_set_header if-match \"\";\n"
      # kubernetes.io/tls-acme: "true"
    tls:
      host: api.ez-sales.eu
      secretName: wildcard-ez-sales-eu-tls
    #tls:
      # Secrets must be manually created in the namespace.
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local
    #tls:
      #- hosts:
      #    - am.example.com
      #  secretName: api-custom-cert
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi
    #  lifecycle:
    #    postStart: '[ "/bin/sh", "-c", "echo Post starting EZ Sales MKP Front" ]'
    #    preStop: '[ "/bin/sh", "-c", "echo Pre stopping EZ Sales MKP Front" ]'
    ## Additional EZ Sales MKP Front volume mounts
    # Defines additional volume mounts.
    # extraVolumeMounts: |
    # - name: extra-volume
    #   mountPath: /mnt/volume
    #   readOnly: true
    #   existingClaim: volume-claim

initContainers:
  image: alpine:latest
  imagePullPolicy: Always
  securityContext:
    runAsUser: 1001
    runAsNonRoot: true
  env: []