apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.api.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.api.name }}
  namespace: {{ .Values.api.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.api.name }}
    spec:
      containers:
      - image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
        name: {{ .Values.api.name }}
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "500Mi"
        envFrom:
        - configMapRef:
            name: ezsales-mkp-api-configmap
        - secretRef:
            name: ezsales-mkp-api-{{ .Values.env }}-secret
      imagePullSecrets:
          - name: registry-secret