apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.api.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.api.name }}
spec:
  ports:
  - name: {{ .Values.api.service.externalPort }}-{{ .Values.api.service.internalPort }}
    port: {{ .Values.api.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.api.service.internalPort }}
  selector:
    app: {{ .Values.api.name }}
status:
  loadBalancer: {}